#spring.application.name=springboot-demo

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:jdbc:mysql://locahost:3306/dusk?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
devtools:
  restart:
    enabled: true  #设置开启热部署
    exclude: static/**, public/**   # 设置不参与热部署的目录或文件，根据需要设置
    weixin:
      appid: 'appid'
      secret: '应用密钥'